doomerhub:
  service:
    search:
      uri: http://localhost:8081
      username: admin_role
      password: "***"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/manager
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search