server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/doomerhub
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/aitranslation
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        use-new-id-generator-mappings: false
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    io.r2dbc.spi: DEBUG

#          docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
#          docker exec -it ollama ollama run deepseek-r1:1.5b

#    docker run --name aitranslation-db -p 5433:5432 -e POSTGRES_DB=aitranslation -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD="@ncHocl&ffkfp)h" postgres:16.1