spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doomerhub
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        use-new-id-generator-mappings: false
server:
  port: 8081
logging:
  level:
    sql: info

#  docker run --name search-db -p 5432:5432 -e POSTGRES_DB=doomerhub -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD="***" postgres:16.1