doomerhub:
  services:
    search:
      uri: http://localhost:8083
    ai:
      uri: http://localhost:8085
server:
  port: 8082
spring:
  main.web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8084/realms/doomerhub
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: author-app
            client-secret: ***
            authorization-grant-type: authorization_code
            scope:
              - openid
              - microprofile-jwt
              - edit_author
              - view_author
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# docker run --name doomerhub-keycloak -p 8084:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=*** -v /config/keycloak/import:/opt/keycloak/data/import quay.io/keycloak/keycloak:23.0.4 start-dev --import-realm