doomerhub:
  services:
    search:
      uri: http://localhost:8083
      username: admin_role
      password: 1234567890
server:
  port: 8082
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/manager
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search