doomerhub:
  services:
    search:
      uri: http://localhost:8081
server:
  port: 8082
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/manager
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search