server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/doomerhub
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/doomerhub
    username: postgres
    password: "***"
  flyway:
    baselineOnMigrate: true
    schema:
      - public
      - search
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        use-new-id-generator-mappings: false
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    io.r2dbc.spi: DEBUG